# Generated by Django 4.2.16 on 2024-10-10 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=20, unique=True)),
                ('rank', models.CharField(max_length=50)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('route', models.TextField()),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_interface.policeofficer')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('THEFT', 'Vol'), ('ASSAULT', 'Agression'), ('VANDALISM', 'Vandalisme'), ('NOISE', 'Tapage'), ('OTHER', 'Autre')], max_length=20)),
                ('area', models.CharField(default='Unknown', max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('concerned_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
                ('reporting_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_interface.policeofficer')),
            ],
        ),
    ]
